import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState, useEffect, useRef } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ['latin'] })

const Middle = dynamic(() => import('./Middle'), {
  ssr: false
})

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.startButtonOuter}>
          <button className={styles.startButtonInner + ' ' + inter.className} onClick={startSeach}>Start</button>
        </div>
        <Middle></Middle>
      </main>
    </>
  )
}

let rotationDeg: number = 90;

function startSeach() {
  let elem = document.getElementsByClassName(styles.middle)[0].children.item(5) as HTMLElement
  elem.style.background = 'red';
  elem.style.transform = 'rotate(' + rotationDeg + 'deg)';
  // rotationDeg += 90;
  // elem.style.transition = 'red 1000ms linear';
}